### ISSUE TITLE
Submission image_url seed causing 400 errors in dev

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#22]
The string "some image_url" is used in the `image_url` field of submissions in the fixtures. It leads to the following exception

```
app_1      | [info] Sent 200 in 40ms
app_1      | [info] GET /submissions/some%20image_url
app_1      | [debug] Processing with AppWeb.SubmissionController.show/2
app_1      |   Parameters: %{"id" => "some image_url"}
app_1      |   Pipelines: [:browser, :auth]
app_1      | [debug] QUERY OK source="users" db=3.9ms queue=0.2ms idle=7205.4ms
app_1      | SELECT u0."id", u0."display_name", u0."email", u0."net_id", u0."is_faculty", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."net_id" = $1) ["stud2"]
app_1      | [info] Sent 400 in 757ms
app_1      | [debug] ** (Ecto.Query.CastError) deps/ecto/lib/ecto/repo/queryable.ex:400: value `"some image_url"` in `where` cannot be cast to type :id in query:
app_1      |
app_1      | from s0 in App.Submissions.Submission,
app_1      |   where: s0.id == ^"some image_url",
app_1      |   select: s0
app_1      |
app_1      |     (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
app_1      |     (elixir) lib/enum.ex:1440: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
app_1      |     (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
app_1      |     (ecto) lib/ecto/repo/queryable.ex:165: Ecto.Repo.Queryable.execute/4
app_1      |     (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
app_1      |     (ecto) lib/ecto/repo/queryable.ex:109: Ecto.Repo.Queryable.one!/3
app_1      |     (app) lib/app_web/controllers/submission_controller.ex:44: AppWeb.SubmissionController.show/2
app_1      |     (app) lib/app_web/controllers/submission_controller.ex:1: AppWeb.SubmissionController.action/2
app_1      |     (app) lib/app_web/controllers/submission_controller.ex:1: AppWeb.SubmissionController.phoenix_controller_pipeline/2
app_1      |     (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
app_1      |     (app) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
app_1      |
```

**Comment by nperanzi** [comment]
This is driven by an HTML element <img src=image_url>; if the image_url is not preceeded by http:// or https://, it is interpreted as a relative URL and the submission_controller attempts to handle it.

Fixed in 881659272d89a86b2ee77e90791b4b60db072238 (note that this implements an additional dependency, EctoFields)
